### ISSUE TITLE
Does not run on wasmer due to getrandom feature

### ISSUE THREAD

**Issue by ThetaSinner** [jedisct1/rust-minisign#27]
I ran into errors running this in WASM on wasmer. The problem is something I've run into a few times which is that `getrandom` with the `js` feature enabled does not work. I need to enable `custom` which I can do but there is no way for me to disable the `js` feature that this crate enables.

I am opening an issue rather than a PR because I can't find a tidy way to fix this.

I changed the `Cargo.toml` from

```toml
[target.'cfg(all(any(target_arch = "wasm32", target_arch = "wasm64"), target_os = "unknown"))'.dependencies]
getrandom = { version = "0.2", optional = false, default-features = false, features = ["js"] }

[target.'cfg(not(all(any(target_arch = "wasm32", target_arch = "wasm64"), target_os = "unknown")))'.dependencies]
getrandom = { version = "0.2", optional = false, default-features = false }

[dependencies]
scrypt = { version = "0.11.0", default-features = false }
```

to

```toml
[dependencies]
scrypt = { version = "0.11.0", default-features = false }
getrandom = { version = "0.2", default-features = false }

[target.'cfg(any(windows, unix))'.dependencies]
rpassword = "7.3.1"

[features]
wasm_js = ["getrandom/js"]
wasm_custom = ["getrandom/custom"]
```

Which I think will work for everyone, but it also means that everyone targeting WASM has to explicitly opt-in to a feature. I'm okay with that for myself and this solves my problem. Any objections to this suggestion?
